# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e406f00a1e6d8f63e449e1d0c830437a4199a64137b769343e9807c40cdf6a0947809630a929e0cc3fa011bf313570984370c4d4c66817c771f11b9912e079

test:
  secret_key_base: e6bea7d2ef043852b368ddb76f33fa582b5d6654c98bc736cd4b3173a5ea599514f263e2d26582ca36920cb9f732af163709c181e1ca419e5dcfcda37b6aae8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
